name: Run Tests
on:
  push:
    branches: [ main ]
jobs:
  test:
    name: Test scripts
    runs-on: ubuntu:latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Execute install scripts
        run: |
          echo "Run scripts"
          ./installations/install_scripts.sh
